name: Development

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    name: Create and push container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: go mod tidy
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/flash_cards_generator
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  clean:
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Clean docker
        run: docker image prune -f
      - name: Clean workspace
        run: rm -rf "${{ github.workspace }}"
