name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install dependencies
        run: go mod tidy
      - name: Test
        env:
          CARDS_SERVERCONFIG: ../router/router.yaml
        run: go test -v ./test
